name: belajar_dart_application
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

publish_to: none # must publish to none if using git

dependencies:
  belajar_dart_packages_library:
    git:
      url: https://github.com/LordRedsky/dart_package_library.git
      ref: 1.5.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
